-- ========================================================
-- 脑卒中患者临床信息 + AI 影像分析结果表
-- ========================================================
-- 1. 清理旧表
DROP TABLE IF EXISTS patient_info CASCADE;

-- 2. 创建表结构
CREATE TABLE patient_info (
  -- 基础身份与主键
  id bigint generated by default as identity primary key,

  -- 临床录入字段 (已移除 NOT NULL，允许 AI 脚本先创建记录)
  patient_name text,
  patient_age int check(patient_age >=0 and patient_age <=120),
  patient_sex text,
  onset_exact_time timestamp with time zone,
  admission_time timestamp with time zone,
  surgery_time text,
  admission_nihss int check(admission_nihss >=0 and admission_nihss <=42),
  nihss_24h int check(nihss_24h >=0 and nihss_24h <=42),
  onset_to_ct_hours FLOAT8 check(onset_to_ct_hours >=0),
  
  -- AI 置信度与体积分析字段
  core_infarct_volume FLOAT8,
  penumbra_volume FLOAT8,
  mismatch_ratio FLOAT8,
  confidence_score FLOAT8,
  core_variance FLOAT8,     -- 从 Mask PNG 计算
  penumbra_variance FLOAT8, -- 从 Mask PNG 计算
  image_noise FLOAT8,       -- 从 CTP NPY 计算
  image_artifact FLOAT8,    -- 从 CTP NPY 计算
  uncertainty_remark TEXT,
  analysis_status TEXT DEFAULT 'pending',

  -- 时间戳
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 3. 开启安全策略 (RLS)
ALTER TABLE patient_info ENABLE ROW LEVEL SECURITY;

-- 4. 配置权限 (适配前端 anon key)
CREATE POLICY "Allow anon insert patient info" ON patient_info FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon select patient info" ON patient_info FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon update patient info" ON patient_info FOR UPDATE TO anon USING (true);
CREATE POLICY "Allow anon delete patient info" ON patient_info FOR DELETE TO anon USING (true);

-- 5. 自动刷新 updated_at 的函数与触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_patient_info_modtime
BEFORE UPDATE ON patient_info
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
